//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 12:45:23 AM EEST 
//


package ee.zalizko.george.eefin.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fieIsikAndmed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fieIsikAndmed">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="isikukood" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="algus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lopp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fieIsikAndmed", namespace = "http://producers.emta.xtee.riik.ee/producer/emta", propOrder = {

})
public class FieIsikAndmed {

    @XmlElement(required = true, nillable = true)
    protected java.lang.String isikukood;
    @XmlElement(required = true, nillable = true)
    protected java.lang.String algus;
    @XmlElement(required = true, nillable = true)
    protected java.lang.String lopp;

    /**
     * Gets the value of the isikukood property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIsikukood() {
        return isikukood;
    }

    /**
     * Sets the value of the isikukood property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIsikukood(java.lang.String value) {
        this.isikukood = value;
    }

    /**
     * Gets the value of the algus property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAlgus() {
        return algus;
    }

    /**
     * Sets the value of the algus property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAlgus(java.lang.String value) {
        this.algus = value;
    }

    /**
     * Gets the value of the lopp property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLopp() {
        return lopp;
    }

    /**
     * Sets the value of the lopp property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLopp(java.lang.String value) {
        this.lopp = value;
    }

}
